name: pyclivac
channels:
  - conda-forge
  - defaults  
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - netcdf4
  - xarray
  - dask
  - bottleneck
  - cartopy
  - seaborn
  - cmocean
  - metpy
  - ipykernel
  - jupyter
  - ffmpeg
  - pip:
    - boto3
